export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SPOTIFY_USER_LOGGED_IN = 'SPOTIFY_USER_LOGGED_IN';
export const SPOTIFY_TOKEN_REFRESHED = 'SPOTIFY_TOKEN_REFRESHED';
